ListenAddr: :8080
UpstreamURL: http://example.com
CookieToBypassCache:
- session-id
Storage:
  Endpoint: https://s3.example.com
  Region: us-east-1
  AccessKeyID: YOUR_ACCESS_KEY_ID
  SecretAccessKey: YOUR_SECRET_ACCESS_KEY
  Bucket: your-bucket-name
Queue:
  KafkaBrokers:
    - kafka-broker-1:9092
    - kafka-broker-2:9092
  KafkaConsumerGroup: inazuma_group
  KafkaTopic: inazuma
  KafkaUpdateTopic: inazuma-update
Redis:
  Addr: redis:6379
  Password: YOUR_REDIS_PASSWORD
  DB: 0
CachePatterns:
- Path: ^/(wiki)/
  ReplaceRules:
  - Match: 1
    Replacements:
    - Replacement: 'zh-hans'
      LanguageMatches: ['zh-hans', 'zh-cn', 'zh-my', 'zh-sg']
    - Replacement: 'zh-hant'
      LanguageMatches: ['zh-hant', 'zh-tw', 'zh-hk', 'zh-mo']
    - Replacement: 'zh'
      Default: true
- Path: ^/zh/
  Purge: true
- Path: ^/zh-hans/
  Purge: true
- Path: ^/zh-hant/
  Purge: true