ListenAddr: :8080
UpstreamURL: http://example.com
CookieToBypassCache: session-id
Storage:
  Endpoint: https://s3.example.com
  Region: us-east-1
  AccessKeyID: YOUR_ACCESS_KEY_ID
  SecretAccessKey: YOUR_SECRET_ACCESS_KEY
  Bucket: your-bucket-name
Queue:
  KafkaBrokers:
    - kafka-broker-1:9092
    - kafka-broker-2:9092
  KafkaConsumerGroup: inazuma_group
  KafkaTopic: inazuma
  KafkaUpdateTopic: inazuma-update
Redis:
  addr: redis:6379
  password: YOUR_REDIS_PASSWORD
  db: 0
